# -*- coding: utf-8 -*-
"""Convert_Temperature.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1p4NReAGbrNceVQyWGft7o5bKnWgPkI3o
"""

Cel = float(input("Write the temperature in Celsius :"))

Fah= (Cel * 9/5) + 32
print(f"The temperature in Fahrenheit is: {Fah}")

